apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: pensjon-saksbehandling
  name: "{{app.name}}"
  namespace: pensjon-saksbehandling
spec:
  ingresses:
    - "{{app.ingress}}"
  image: {{image}}
  port: 8080
  replicas:
    max: 2
    min: 2
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: "{{app.database}}"
            envVarPrefix: POSTGRES
        pointInTimeRecovery: false
        retainedBackups: 1
  accessPolicy:
    inbound:
      rules:
        - application: "{{ruter.name}}"
  liveness:
    path: "/actuator/health/liveness"
    initialDelay: 10
  readiness:
    path: "/actuator/health/readiness"
    initialDelay: 10
  startup:
    path: "/actuator/health/readiness"
    initialDelay: 10
    failureThreshold: 100
    periodSeconds: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
